### PR TITLE
update change log for #62

### PR DESCRIPTION
**Pull request by stdrc**

### CODE REVIEW

**Review by wangrunji0408 — COMMENTED** [review]
Should be changed in the changelog in arrow-udf-flight?

**Comment by stdrc** [comment]
> Should be changed in the changelog in arrow-udf-flight?

Oh, yes. I'm stupid🤡

**Comment by stdrc** [comment]
Shall we also bump `arrow-udf-flight` to `0.4.0`?

**Review by wangrunji0408 — COMMENTED** [review]
After a closer look, I suggest to keep the original `new` method and introduce a new `new_from_inner` for the lower level client ([ref](https://docs.rs/arrow-flight/53.1.0/arrow_flight/client/struct.FlightClient.html#method.new_from_inner)). This way, users won't touch the `arrow_flight` crate if they don't need customization.

**Comment by Xuanwo** [comment]
> After a closer look, I suggest to keep the original `new` method and introduce a new `new_from_inner` for the lower level client ([ref](https://docs.rs/arrow-flight/53.1.0/arrow_flight/client/struct.FlightClient.html#method.new_from_inner)). This way, users won't touch the `arrow_flight` crate if they don't need customization. If we do this, the version can be bumped to 0.3.1.

We are going to update the arrow and tonic versions in https://github.com/arrow-udf/arrow-udf/pull/70 so that these changes can be released simultaneously. How about releasing them as breaking changes as is?

**Comment by wangrunji0408** [comment]
> > After a closer look, I suggest to keep the original `new` method and introduce a new `new_from_inner` for the lower level client ([ref](https://docs.rs/arrow-flight/53.1.0/arrow_flight/client/struct.FlightClient.html#method.new_from_inner)). This way, users won't touch the `arrow_flight` crate if they don't need customization. If we do this, the version can be bumped to 0.3.1.
> 
> We are going to update the arrow and tonic versions in #70 so that these changes can be released simultaneously. How about releasing them as breaking changes as is?

LGTM. No problem.

**Review by Xuanwo — APPROVED** [review]
Thanks!

**Pull request merged**
