### PR TITLE
deps: Bump arrow 53, tonic 0.12

### PR DESCRIPTION
**Pull request by Xuanwo**

### CODE REVIEW

**Comment by BugenZhao** [comment]
Let's make it happen 🚀🚀🚀🚀

**Review by xxchan — APPROVED** [review]

**Comment by Xuanwo** [comment]
There are some SIGABR after upgrading, I'm working on this now.

**Comment by Xuanwo** [comment]
After the bisect, I discovered that PyO3 was broken following the commit: https://github.com/PyO3/pyo3/commit/1c64a03ea084852572872c0d6b5fd029f116c807.

I'm afraid we can't upgrade pyo3 in our current way. I will discuss with the upstream first.

**Review by fuyufjh — APPROVED** [review]

**Comment by fuyufjh** [comment]
Shall we publish a new version to unblock https://github.com/risingwavelabs/risingwave/pull/18682?

**Comment by xxchan** [comment]
I’m on vacation. Maybe @stdrc want to do it

**Comment by stdrc** [comment]
IIUC, we need to bump and publish new minor version for `arrow-udf-flight`, `arrow-udf-python` and `arrow-udf`, right?

**Comment by fuyufjh** [comment]
> IIUC, we need to bump and publish new minor version for `arrow-udf-flight`, `arrow-udf-python` and `arrow-udf`, right?

`arrow-udf-flight` seems to be the only one depending on `tonic`?

**Comment by stdrc** [comment]
> > IIUC, we need to bump and publish new minor version for `arrow-udf-flight`, `arrow-udf-python` and `arrow-udf`, right?
> 
> `arrow-udf-flight` seems to be the only one depending on `tonic`?

Never mind, just bumped them all https://github.com/arrow-udf/arrow-udf/pull/76.

**Pull request merged**
